name: Build And Pubish
run-name: Build And Pubish by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  set-up-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20

  build-and-publish:
    runs-on: ubuntu-latest
    needs: set-up-node
    steps:
      - name: check-out
        uses: actions/checkout@v4

      - name: Install
        shell: bash
        run: |
          yarn
          yarn add yakumo typescript yakumo-esbuild yakumo-esbuild-yaml yakumo-publish yakumo-publish-sync yakumo-mocha mocha esbuild yakumo-tsc yml-register esbuild-register -D

      - name: Eslint
        shell: bash
        run: yarn eslint ./src

      - name: Build
        shell: bash
        run: |
          cat package.json
          echo "require:
          - esbuild-register
          - yakumo-esbuild
          - yakumo-esbuild-yaml
          - yakumo-mocha
          - yakumo-publish
          - yakumo-publish-sync
          - yakumo-tsc
          pipeline:
            build:
              - tsc
              - esbuild" > yakumo.yml
          yarn yakumo build

      - name: Set npm token
        shell: bash
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN_KOISHI }}" > ~/.npmrc

      - name: Publish package
        shell: bash
        run: yarn yakumo publish --debug
