name: Build And Pubish
run-name: Build And Pubish by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'npm token used to publish'
        required: true
      node-version:
        default: '20'
        required: false
        description: Node.js version to use
      otp-code:
        default: ''
        required: false
        description: '2FA Authenticate code'

jobs:
  set-up-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
  build-and-publish:
    runs-on: ubuntu-latest
    needs: set-up-node
    steps:
      - name: check-out
        uses: actions/checkout@v4
      - name: Install
        shell: bash
        run: |
          pwd
          ls
          yarn add install-peers
          yarn
          yarn add @types/node @types/react esbuild esbuild-register globals tsx typescript yakumo yakumo-esbuild yakumo-tsc yml-register yakumo-publish -D

      - name: Build
        shell: bash
        run: |
          echo "require:
            - yakumo-esbuild
            - yakumo-publish
            - yakumo-tsc
          pipeline:
            build:
              - tsc
              - esbuild" > yakumo.yml
          pwd
          ls
          cat package.json
          yarn yakumo build

      - name: Set npm token
        shell: bash
        run: echo "//registry.npmjs.org/:_authToken=${{ inputs.token }}" > ~/.npmrc

      - name: Publish package
        shell: bash
        run: yarn yakumo publish --otp=${{ inputs.otp-code }}
