name: Build And Pubish
run-name: Build And Pubish by @${{ github.actor }}

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install
        shell: bash
        run: |
          yarn
          yarn add yakumo typescript yakumo-esbuild yakumo-esbuild-yaml yakumo-publish yakumo-publish-sync yakumo-mocha mocha esbuild yakumo-tsc yml-register esbuild-register -D

      - name: Eslint
        shell: bash
        run: yarn eslint ./src

      - name: Build
        shell: bash
        run: |
          echo "require:
          - esbuild-register
          - yakumo-esbuild
          - yakumo-esbuild-yaml
          - yakumo-mocha
          - yakumo-publish
          - yakumo-publish-sync
          - yakumo-tsc
          pipeline:
            build:
              - tsc
              - esbuild" > yakumo.yml
          yarn yakumo build

      - name: Publish package
        shell: bash
        run: yarn yakumo publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_KOISHI }}
