name: Build And Pubish
run-name: Build And Pubish by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  set-up-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20

  build-and-publish:
    runs-on: ubuntu-latest
    needs: set-up-node
    steps:
      - name: check-out
        uses: actions/checkout@v4
      - name: Install
        shell: bash
        run: |
          yarn
          yarn add @types/node @types/react esbuild esbuild-register globals tsx typescript yakumo yakumo-esbuild yakumo-tsc yml-register yakumo-publish -D
          npm install

      - name: Build
        shell: bash
        run: |
          echo "require:
            - yakumo-esbuild
            - yakumo-publish
            - yakumo-tsc
          pipeline:
            build:
              - tsc
              - esbuild" > yakumo.yml
          cat package.json
          yarn yakumo build

      - name: Set npm token
        shell: bash
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN_KOISHI }}" > ~/.npmrc

      - name: Publish package
        shell: bash
        run: yarn yakumo publish
